# Generated by Django 5.2 on 2025-04-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubject',
            name='name_en_GB',
            field=models.CharField(help_text='Contact Subject Name', max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='contactsubject',
            name='name_pt_PT',
            field=models.CharField(help_text='Contact Subject Name', max_length=100, null=True, verbose_name='Name'),
        ),
    ]
