# Generated by Django 5.2.5 on 2025-08-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the contact request was created', null=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='read_at',
            field=models.DateTimeField(blank=True, help_text='When the contact request was read', null=True, verbose_name='Read At'),
        ),
    ]
