# Generated by Django 5.2.5 on 2025-08-29 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0002_contactrequest_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactrequest',
            options={'ordering': ['-created_at']},
        ),
    ]
