# Generated by Django 5.2.5 on 2025-08-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='is_allergic',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='is_medicated',
        ),
        migrations.AlterField(
            model_name='pet',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The height of the pet in centimeters', max_digits=5, null=True, verbose_name='height (cm)'),
        ),
    ]
