# Generated by Django 5.2 on 2025-04-18 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The weight of the pet in centimeters', max_digits=5, null=True, verbose_name='weight (cm)'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The weight of the pet in kilograms', max_digits=5, null=True, verbose_name='weight (kg)'),
        ),
    ]
