# Generated by Django 5.2 on 2025-04-22 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('terms', 'Terms and Conditions'), ('privacy', 'Privacy Policy')], help_text='Select whether this is a Terms and Conditions or Privacy Policy document.', max_length=20, unique=True, verbose_name='Document Type')),
                ('title', models.CharField(blank=True, help_text='Main title of the legal document shown to users.', max_length=255, verbose_name='Title')),
                ('title_en_GB', models.CharField(blank=True, help_text='Main title of the legal document shown to users.', max_length=255, null=True, verbose_name='Title')),
                ('title_pt_PT', models.CharField(blank=True, help_text='Main title of the legal document shown to users.', max_length=255, null=True, verbose_name='Title')),
                ('effective_date', models.DateField(help_text='Date from which this document is considered effective.', verbose_name='Effective Date')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Automatically updated whenever the document is changed.', verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'Legal Document',
                'verbose_name_plural': 'Legal Documents',
            },
        ),
        migrations.CreateModel(
            name='LegalDocumentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the section (e.g., Reservations, Data Collection, etc.).', max_length=255, verbose_name='Section Title')),
                ('title_en_GB', models.CharField(help_text='Title of the section (e.g., Reservations, Data Collection, etc.).', max_length=255, null=True, verbose_name='Section Title')),
                ('title_pt_PT', models.CharField(help_text='Title of the section (e.g., Reservations, Data Collection, etc.).', max_length=255, null=True, verbose_name='Section Title')),
                ('order', models.PositiveIntegerField(default=0, help_text='Defines the display order of sections within the document.', verbose_name='Order')),
                ('document', models.ForeignKey(help_text='The legal document this section belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='backoffice.legaldocument', verbose_name='Document')),
            ],
            options={
                'verbose_name': 'Legal Section',
                'verbose_name_plural': 'Legal Sections',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LegalDocumentSectionLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The actual content of this line item (e.g., a clause, condition, or explanation).', verbose_name='Text')),
                ('text_en_GB', models.TextField(help_text='The actual content of this line item (e.g., a clause, condition, or explanation).', null=True, verbose_name='Text')),
                ('text_pt_PT', models.TextField(help_text='The actual content of this line item (e.g., a clause, condition, or explanation).', null=True, verbose_name='Text')),
                ('order', models.PositiveIntegerField(default=0, help_text='Defines the display order of line items within the section.', verbose_name='Order')),
                ('section', models.ForeignKey(help_text='The section this line item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='backoffice.legaldocumentsection', verbose_name='Section')),
            ],
            options={
                'verbose_name': 'Line Item',
                'verbose_name_plural': 'Line Items',
                'ordering': ['order'],
            },
        ),
    ]
