# Generated by Django 5.2 on 2025-04-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legaldocument',
            name='title',
        ),
        migrations.RemoveField(
            model_name='legaldocument',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='legaldocument',
            name='title_pt',
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='heading',
            field=models.TextField(blank=True, help_text='Heading of the legal document.', null=True, verbose_name='Heading'),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='heading_en',
            field=models.TextField(blank=True, help_text='Heading of the legal document.', null=True, verbose_name='Heading'),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='heading_pt',
            field=models.TextField(blank=True, help_text='Heading of the legal document.', null=True, verbose_name='Heading'),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the legal document shown to users.', max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='name_en',
            field=models.CharField(blank=True, help_text='Name of the legal document shown to users.', max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='name_pt',
            field=models.CharField(blank=True, help_text='Name of the legal document shown to users.', max_length=255, null=True, verbose_name='Name'),
        ),
    ]
