# Generated by Django 5.2 on 2025-04-22 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legaldocument',
            options={'ordering': ['-effective_date', '-updated_at'], 'verbose_name': 'Legal Document', 'verbose_name_plural': 'Legal Documents'},
        ),
        migrations.RemoveField(
            model_name='legaldocument',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, help_text='Marks this document as deleted/deprecated.', null=True, verbose_name='Deleted At'),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Automatically updated whenever the document is changed.', verbose_name='Last Updated At'),
        ),
        migrations.AlterField(
            model_name='legaldocumentsection',
            name='document',
            field=models.ForeignKey(help_text='The legal document this section belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='sections', related_query_name='section', to='backoffice.legaldocument', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='legaldocumentsection',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text='Defines the display order of sections within the document.', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='legaldocumentsectionlineitem',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text='Defines the display order of line items within the section.', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='legaldocumentsectionlineitem',
            name='section',
            field=models.ForeignKey(help_text='The section this line item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='items', related_query_name='item', to='backoffice.legaldocumentsection', verbose_name='Section'),
        ),
    ]
