# Generated by Django 5.2 on 2025-04-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_alter_legaldocument_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legaldocument',
            name='doc_type',
            field=models.CharField(choices=[('terms', 'Terms and Conditions'), ('privacy', 'Privacy Policy')], help_text='Select whether this is a Terms and Conditions or Privacy Policy document.', max_length=20, verbose_name='Document Type'),
        ),
    ]
