# Generated by Django 5.2.5 on 2025-08-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toconline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toconlinetoken',
            name='refreshed_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
