# Generated by Django 5.2.5 on 2025-08-29 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toconline', '0002_toconlinetoken_refreshed_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toconlinetoken',
            options={'ordering': ['-refreshed_at', '-acquired_at']},
        ),
    ]
