# Generated by Django 5.2 on 2025-04-18 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toconline_customer_id', models.CharField(blank=True, db_index=True, help_text='The ID of the customer in the toconline platform (invoice system)', max_length=100, null=True, unique=True, verbose_name='Customer ID (toconline)')),
                ('user', models.OneToOneField(help_text='The user that this account belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='account', related_query_name='account', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
