# Generated by Django 5.2 on 2025-04-18 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel', '0001_initial'),
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingservice',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pets.pet'),
        ),
        migrations.AddField(
            model_name='bookingstay',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stays', related_query_name='stay', to='hotel.booking'),
        ),
        migrations.AddField(
            model_name='bookingstay',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pets.pet'),
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='stay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', related_query_name='service', to='hotel.bookingstay'),
        ),
    ]
