# Generated by Django 5.2 on 2025-04-24 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingservice',
            old_name='service_id',
            new_name='stripe_product_id',
        ),
        migrations.RenameField(
            model_name='bookingstay',
            old_name='stay_id',
            new_name='stripe_product_id',
        ),
        migrations.RemoveField(
            model_name='bookingservice',
            name='service_name',
        ),
        migrations.RemoveField(
            model_name='bookingservice',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='bookingservice',
            name='unit_price_eur',
        ),
        migrations.RemoveField(
            model_name='bookingstay',
            name='stay_name',
        ),
        migrations.RemoveField(
            model_name='bookingstay',
            name='unit_price_eur',
        ),
    ]
