# Generated by Django 5.2 on 2025-04-22 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_initial'),
        ('pets', '0002_alter_pet_height_cm_alter_pet_weight_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='toconline_sale_document_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bookingstay',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_stays', related_query_name='booking_stay', to='pets.pet'),
        ),
    ]
