# Generated by Django 5.2 on 2025-04-24 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_rename_service_id_bookingservice_stripe_product_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='stripe_session_id',
            new_name='stripe_checkout_session_id',
        ),
    ]
