# Generated by Django 5.2.4 on 2025-07-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_rename_stripe_session_id_booking_stripe_checkout_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='toconline_amend_document_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
