# Generated by Django 5.2.5 on 2025-08-29 14:15

import django.db.models.deletion
import hotel.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_booking_toconline_amend_document_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingStayMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=hotel.models.stay_media_upload_to)),
                ('content_type', models.CharField(blank=True, max_length=128)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('size', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_stay_media', to=settings.AUTH_USER_MODEL)),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', related_query_name='medium', to='hotel.bookingstay')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
